### ISSUE TITLE
帮帮

### ISSUE THREAD

**Issue by runjiekang** [IrumaMegumi/ROS-notes#1]
你搞点云目标检测嘛，可以救一下嘛

**Comment by IrumaMegumi** [comment]
你好，请问你是打RM的吗

**Comment by runjiekang** [comment]
demo 租的服务器，
 `(openpcdet) ***@***.***:~/OpenPCDet/tools$ python demo.py --cfg_file cfgs/kitti_models/pointpillar.yaml --ckpt pointpillar_7728.pth --data_path 000008.bin
2023-10-26 13:46:21,971 INFO -----------------Quick Demo of OpenPCDet-------------------------
2023-10-26 13:46:21,971 INFO Total number of samples: 1
/home/thiesy/miniconda3/envs/openpcdet/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/native/TensorShape.cpp:2157.)
return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined]
2023-10-26 13:46:23，601 INFO ==> Loading parameters from checkpoint pointpillar_7728.pth to CPU
2023-10-26 13:46:23,613 INFO ==> Done (loaded 127/127)
2023-10-26 13:46:23,626 INFO Visualized sample index: 1
No protocol specified

[Open3D WARNING] GLFW Error: X11: Failed to open display :0.0
[Open3D WARNING] Failed to initialize GLFW
Traceback (most recent call last):
File "demo.py", line 112, in
main()
File "demo.py", line 100, in main
V.draw_scenes(
File "/home/thiesy/OpenPCDet/tools/visual_utils/open3d_vis_utils.py", line 49, in draw_scenes
vis.get_render_option().point_size = 1.0
AttributeError: 'NoneType' object has no attribute 'point_size'

发件人：IrumaMegumi ***@***.***>
发送日期：2023-10-28 19:49:56
收件人：IrumaMegumi/ROS-notes ***@***.***>
抄送人：runjiekang ***@***.***>,Author ***@***.***>
主题：Re: [IrumaMegumi/ROS-notes] 帮帮 (Issue #1)

你好，请问你是打RM的吗

**Comment by IrumaMegumi** [comment]
是的

**Comment by runjiekang** [comment]
请问你知道是什么原因嘛

**Comment by IrumaMegumi** [comment]
我没遇到过这个问题，但是我感觉是路径的原因，可以加我qq：2286453531交流下
